Initialize project
Rustamxon7/BookStore-React-Redex pull request #1
Opened 2021-10-04 19:19 UTC by Rustamxon7

**Bookstore: initialize the project with components**

All requirements are completed: 

- React App is initialized 💯 
- React Redux added 💯 
- Used ducks pattern for Redux files 💯 

Feel free to review -🧑🏻‍💻 - my project and let me know if there are any changes to do. -🤓 -

2021-10-04 22:06 UTC, EricMbouwe requested changes
Hi @Rustamxon7,

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-04 22:06 UTC, EricMbouwe commented on src/components/bookstore/Book.js
> +    <p style={{ width: '10rem' }}>{title}</p>
- [ ] You don't need to add the `key` attribute here, It is needed where you have used the map function, Keys help React identify which items have changed, are added, or are removed. Keys should be given to the elements inside the array to give the elements a stable identity. You can learn more about it [here](https://reactjs.org/docs/lists-and-keys.html)

Here is an example
```
const todoItems = todos.map((todo) =>
  <li key={todo.id}>
    {todo.text}
  </li>
```

2021-10-05 01:33 UTC, Rustamxon7 commented on src/components/bookstore/Book.js
> +    <p style={{ width: '10rem' }}>{title}</p>
Thank you again for reminding me about that.
And take a look at the solutions for this issues and let me know if I did correct. If I couldn't do as you requested, I would be very happy for explaining me the problem again. You can consider me as a new student for React&Redux.... 
**_Happy Reviewing!_**

2021-10-05 01:33 UTC, Rustamxon7 commented on src/components/bookstore/List.js
> +    </ul>
This issue is also being complete!

2021-10-05 01:33 UTC, Rustamxon7 commented on src/components/bookstore/Input.js
> +  </form>
Thank you so much reminding me! I didn't pay attention for that. But this time I hope it is done!

2021-10-05 06:30 UTC, arslanbisharat approved these changes
# Approved 👏 

Hi there, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error is present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

2021-10-05 06:31 UTC, merged